### PR TITLE
CI: add some simple header checks.

### LINKED ISSUE #1572: CI: header checks
It would be good to add another CI job that does some basic header / formatting checks:
1. Verify that IBTK headers include `ibtk/config.h` and IBAMR headers include `ibamr/config.h`
2. Verify that we always use `<ibamr/header.h>` and not `"ibamr/header.h"`
3. Verify that headers can be compiled independently (`g++ -E` is a very fast way to check this)

Like the other CI stuff this should be done after we get in all the phase-change code so we don't break mostly-done PRs.

### PR DESCRIPTION
**Pull request by drwells**
Fixes #1572.

~I need to add one more check but let me first ensure the first two are working.~ I added the missing check and everything looks good.

### CODE REVIEW

**Comment by boyceg** [comment]
Looks good. Are some of these changes because of a change in the autotools versions?

**Comment by drwells** [comment]
There's something screwy going on with how our config file shims are defined for autotools:
```

2023-05-13T15:12:21.5775972Z In file included from ../../../tests/IBTK/version_macros.cpp:14:
2023-05-13T15:12:21.5776419Z ../../../include/ibamr/config.h:38:67: error: missing binary operator before token "("
2023-05-13T15:12:21.5776837Z    38 | #define IBAMR_VERSION_GTE(major, minor, subminor) IBTK_VERSION_GTE(major, minor, subminor)
2023-05-13T15:12:21.5777176Z       |                                                                   ^
```
I haven't had a chance to debug it yet.

**Comment by drwells** [comment]
I think its worth adding - the extra checks found a few minor problems (mostly headers which can't be compiled on their own).
